<?xml version="1.0" encoding="UTF-8"?><testrun name="OperacionesMatematicasTest" project="Programacion-Orientada-Objeto" tests="4" started="4" failures="1" errors="0" ignored="0">
  <testsuite name="com.cursojava04.modulo4.junit.OperacionesMatematicasTest" time="0.046" displayname="OperacionesMatematicasTest" uniqueid="[engine:junit-jupiter]/[class:com.cursojava04.modulo4.junit.OperacionesMatematicasTest]">
    <testcase name="testSumar" classname="com.cursojava04.modulo4.junit.OperacionesMatematicasTest" time="0.0" displayname="testSumar()" uniqueid="[engine:junit-jupiter]/[class:com.cursojava04.modulo4.junit.OperacionesMatematicasTest]/[method:testSumar()]"/>
    <testcase name="testMultiplicar" classname="com.cursojava04.modulo4.junit.OperacionesMatematicasTest" time="0.0" displayname="testMultiplicar()" uniqueid="[engine:junit-jupiter]/[class:com.cursojava04.modulo4.junit.OperacionesMatematicasTest]/[method:testMultiplicar()]"/>
    <testcase name="testDividir" classname="com.cursojava04.modulo4.junit.OperacionesMatematicasTest" time="0.042" displayname="testDividir()" uniqueid="[engine:junit-jupiter]/[class:com.cursojava04.modulo4.junit.OperacionesMatematicasTest]/[method:testDividir()]">
      <failure>java.lang.AssertionError: unexpected exception type thrown; expected:&lt;java.lang.IllegalArgumentException&gt; but was:&lt;java.lang.ArithmeticException&gt;&#13;
	at org.junit.Assert.assertThrows(Assert.java:1020)&#13;
	at org.junit.Assert.assertThrows(Assert.java:981)&#13;
	at com.cursojava04.modulo4.junit.OperacionesMatematicasTest.testDividir(OperacionesMatematicasTest.java:63)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at java.util.ArrayList.forEach(Unknown Source)&#13;
	at java.util.ArrayList.forEach(Unknown Source)&#13;
Caused by: java.lang.ArithmeticException: / by zero&#13;
	at com.cursojava04.modulo4.junit.OperacionesMatematicas.dividir(OperacionesMatematicas.java:18)&#13;
	at com.cursojava04.modulo4.junit.OperacionesMatematicasTest.lambda$0(OperacionesMatematicasTest.java:63)&#13;
	at org.junit.Assert.assertThrows(Assert.java:1001)&#13;
	... 5 more&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testRestar" classname="com.cursojava04.modulo4.junit.OperacionesMatematicasTest" time="0.002" displayname="testRestar()" uniqueid="[engine:junit-jupiter]/[class:com.cursojava04.modulo4.junit.OperacionesMatematicasTest]/[method:testRestar()]"/>
  </testsuite>
</testrun>
